name: Provision AWS Infrastructure

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: Apply Terraform configuration
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0  # Specify the Terraform version you want to use

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2  # Specify your AWS region

    - name: Initialize Terraform
      run: terraform init

    - name: Plan Terraform
      run: terraform plan

    - name: Apply Terraform
      if: github.ref == 'refs/heads/main'  # Only apply on pushes to main branch
      run: terraform apply -auto-approve

    - name: Terraform output
      run: terraform output